### ISSUE TITLE
Идея для нового предмета

### ISSUE THREAD

**Issue by dest4590** [adasdead/strangemod#21]
предмет poco x3 pro

при использовании предмета будет играть песня [omagad poco](https://www.youtube.com/watch?v=kdplodX990Y), после чего будет происходить взрыв

**Comment by dest4590** [comment]
также даю текстуру

<img src="https://github.com/adasdead/strangemod/assets/80628386/6e50137a-8cc6-44d3-8b6c-505200928717" width=200>

**Comment by iwtsyd-none** [comment]
АХААХХАХАЭАХАХАХЭАХАХАХАХАХАХ

**Comment by Slieko** [comment]
завтра сделаю
